#!/bin/bash

BRUTE=$1
MODEL=$2
GEN=$3

./c $GEN
./c $BRUTE
./c $MODEL

for test in {1..1000000}; do
    echo $test
    ./$GEN > test.in
    ./$BRUTE < test.in > brut.out
    ./$MODEL < test.in > wzo.out

    diff brut.out wzo.out || break
done

echo "OJEJKU"